# Platform
TARGET_BOARD_PLATFORM := mt6572

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := krait

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := mt6572

# Kernel
TARGET_PREBUILT_KERNEL := device/F605/F605/kernel
BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_TAGS_OFFSET := 0x00000100
BOARD_SECOND_OFFSET := 0x00f00000
BOARD_KERNEL_SEPARATED_DT := true
#BOARD_MKBOOTIMG_ARGS := --base $(BOARD_KERNEL_BASE) --pagesize $(BOARD_KERNEL_PAGESIZE) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --board $(BOARD_NAME) --cmdline $(BOARD_KERNEL_CMDLINE)
BOARD_CUSTOM_BOOTIMG_MK := device/advan/mt6572-common/prebuilt_boot.mk
#    --kernel_offset $(BOARD_KERNEL_OFFSET) \
#    --tags_offset $(BOARD_TAGS_OFFSET) \
#    --second_offset $(BOARD_SECOND_OFFSET) \

TARGET_RECOVERY_FSTAB := device/F605/F605/recovery/root/etc/recovery.fstab

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x600000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x600000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x39800000
BOARD_CACHEIMAGE_PARTITION_SIZE := 0x700000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0xfe00000

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
BOARD_SUPPRESS_EMMC_WIPE := true

TW_INTERNAL_STORAGE_PATH := /data/media
TW_INTERNAL_STORAGE_MOUNT_POINT := sdcard
TW_EXTERNAL_STORAGE_PATH := /external_sd
TW_EXTERNAL_STORAGE_MOUNT_POINT := external_sd

# USB Mounting
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/virtual/android_usb/android0/f_mass_storage/lun/file

TW_THEME=portrait_hdpi
BOARD_FLASH_BLOCK_SIZE := 0x20000
TW_NO_EXFAT_FUSE := true
TW_EXCLUDE_SUPERSU := true
TW_INCLUDE_CRYPTO := false
TW_EXCLUDE_CRYPTO := true
TW_NO_EXFAT := true
TW_EXCLUDE_MTP := true
TW_NO_USB_STORAGE := true
TWHAVE_SELINUX := false
TW_EXCLUDE_ENCRYPTED_BACKUPS := true
BOARD_HAS_NO_REAL_SDCARD := true
